# Generated by Django 3.1.14 on 2022-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('ML', 'MALE'), ('FM', 'FEMALE'), ('PN', 'PREFERS NOT TO SAY'), ('OT', 'OTHERS')], default='PN', max_length=2),
        ),
    ]
