# Generated by Django 3.1.14 on 2022-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='delivery_address',
            field=models.ManyToManyField(blank=True, related_name='delivery_address', to='users.UserAddressModel', verbose_name='user delivery address'),
        ),
    ]
