# Generated by Django 4.0.5 on 2022-06-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20220612_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('deleted_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('data_status', models.BooleanField(default=True)),
                ('discount_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='ProductCountModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'ProductCount',
            },
        ),
        migrations.CreateModel(
            name='Tagmodel',
            fields=[
                ('deleted_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('data_status', models.BooleanField(default=True)),
                ('tag_img', models.ImageField(upload_to='tag_image/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('deleted_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('data_status', models.BooleanField(default=True)),
                ('partners', models.ManyToManyField(blank=True, related_name='partners', to=settings.AUTH_USER_MODEL, verbose_name='partners of Shop')),
                ('shop_address', models.ManyToManyField(blank=True, related_name='shop_address', to='users.useraddressmodel', verbose_name='shop address')),
                ('shop_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner of the shop')),
                ('shop_prouducts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.productcountmodels')),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('deleted_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('data_status', models.BooleanField(default=True)),
                ('product_images', models.ImageField(upload_to='images/')),
                ('product_measuring_choices', models.CharField(choices=[('CM', 'COUNTABLE PRODUCT'), ('MM', 'MEASURABLE PRODUCT'), ('SC', 'SIMPLE COUNTABLE PRODUCT')], default='SC', max_length=2)),
                ('price_of_product_single_unit', models.IntegerField()),
                ('product_measure_unit', models.CharField(choices=[('KG', 'KiloGram'), ('GR', 'Gram'), ('LT', 'Litre'), ('KL', 'KiloLitre'), ('CT', 'NORMAL COUNTABLE')], default='CT', max_length=2)),
                ('discount', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.discountmodel')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_product', to='shops.tagmodel')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AddField(
            model_name='productcountmodels',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.productmodel'),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('deleted_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('data_status', models.BooleanField(default=True)),
                ('Users', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_cart', to=settings.AUTH_USER_MODEL)),
                ('product_count_map', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.productcountmodels')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
