# Generated by Django 3.1.14 on 2022-06-07 10:06

from django.db import migrations, models
import uuid
from ..models.ProductModel import validate_amount

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('product_count', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasuringModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_unit', models.CharField(choices=[('CT', 'Countable Quantity'), ('MS', 'Measurable Quantity')], default='CT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMeasureModel',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PouchModel',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('amount', models.IntegerField(unique=True, validators=[validate_amount])),
                ('unit', models.CharField(choices=[('KG', 'KiloGram'), ('GR', 'Gram'), ('LT', 'Litre'), ('KL', 'KiloLitre')], default='GR', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCountableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.IntegerField(validators=[validate_amount])),
                ('quantity_count', models.IntegerField(validators=[validate_amount])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMeasurableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.IntegerField(validators=[validate_amount])),
                ('quantity_count', models.IntegerField(validators=[validate_amount])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('product_images', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
                ('order_status', models.CharField(choices=[('OD', 'Order Delivered'), ('OW', 'On The Way'), ('PP', 'Packaging Process Is Going On'), ('OS', 'Out For Shipping'), ('NA', 'Not Avaliable Service right now')], default='OW', max_length=2)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
