# Generated by Django 3.1.14 on 2022-06-07 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.useraddressmodel'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='ordered_prod',
            field=models.ManyToManyField(to='shops.OrderMeasureModel'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_to_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partners', to=settings.AUTH_USER_MODEL, verbose_name='partners of Shop'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shop_address',
            field=models.ManyToManyField(blank=True, related_name='shop_address', to='users.UserAddressModel', verbose_name='shop address'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shop_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner of the shop'),
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shop_prouducts',
            field=models.ManyToManyField(blank=True, to='shops.ProductModel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='measuring_params',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.measuringmodel'),
        ),
        migrations.AddField(
            model_name='productmeasurablemodel',
            name='pouch_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.pouchmodel'),
        ),
        migrations.AddField(
            model_name='ordermeasuremodel',
            name='measure_params',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.measuringmodel'),
        ),
        migrations.AddField(
            model_name='ordermeasuremodel',
            name='ordered_prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.productmodel'),
        ),
        migrations.AddField(
            model_name='measuringmodel',
            name='countable_product',
            field=models.ManyToManyField(blank=True, to='shops.ProductCountableModel'),
        ),
        migrations.AddField(
            model_name='measuringmodel',
            name='measurable_product',
            field=models.ManyToManyField(blank=True, to='shops.ProductMeasurableModel'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='Users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_product',
            field=models.ManyToManyField(blank=True, related_name='items_in_cart', to='shops.OrderMeasureModel'),
        ),
    ]
