# Generated by Django 3.1.14 on 2022-06-10 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20220607_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagmodel',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='default', max_length=255)),
                ('description', models.CharField(blank=True, default=' default description', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='related_tags',
            field=models.ManyToManyField(related_name='tags_product', to='shops.Tagmodel', verbose_name='tags according to product'),
        ),
    ]
