# Generated by Django 4.0.5 on 2022-06-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_productmodel_discount_alter_productmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmodel',
            name='shop_prouducts',
        ),
        migrations.AddField(
            model_name='shopmodel',
            name='shop_prouducts',
            field=models.ManyToManyField(blank=True, to='shops.productcountmodels'),
        ),
    ]
