# Generated by Django 3.1.14 on 2022-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20220610_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='measuring_choices',
            field=models.CharField(choices=[('CT', 'Countable Quantity'), ('MS', 'Measurable Quantity')], default='SC', max_length=2),
        ),
    ]
