# Generated by Django 3.1.14 on 2022-06-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_productmodel_measuring_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='measuring_choices',
            field=models.CharField(choices=[('CT', 'Countable Quantity'), ('MS', 'Measurable Quantity')], max_length=2),
        ),
    ]
