# Generated by Django 3.1.14 on 2022-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20220612_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='measuring_choices',
            field=models.CharField(choices=[('CM', 'COUNTABLE PRODUCT'), ('MM', 'MEASURING PRODUCT'), ('SC', 'SIMPLE COUNTABLE PRODUCT')], default='SC', max_length=2),
        ),
    ]
