# Generated by Django 3.1.14 on 2022-06-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20220612_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='measuring_params',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.measuringmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='related_tags',
            field=models.ManyToManyField(blank=True, related_name='tags_product', to='shops.Tagmodel', verbose_name='tags according to product'),
        ),
    ]
