# Generated by Django 3.1.14 on 2022-06-13 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20220612_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='measuring_params',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.measuringmodel'),
        ),
    ]
